# Generated by Django 2.2.12 on 2020-06-12 05:02

from django.db import migrations, models
import shopify_store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyCustomerFingerPrint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(default=None, help_text='Shopify customer ID', unique=True)),
                ('fingerprint_file', models.FileField(default=None, help_text='Customer Fingerprint File', upload_to=shopify_store.models.shopify_customer_fingerprint_directory_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer Fingerprint',
                'verbose_name_plural': 'Customer Fingerprints',
                'ordering': ('-created',),
            },
        ),
    ]
