# Generated by Django 2.2.12 on 2020-06-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifycustomerfingerprint',
            name='customer_id',
            field=models.IntegerField(default=None, help_text='Shopify customer ID'),
        ),
    ]
