# Generated by Django 2.2.12 on 2020-06-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_store', '0002_auto_20200612_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifycustomerfingerprint',
            name='fingerprint_title',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
