# Generated by Django 2.2.12 on 2020-06-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_store', '0003_shopifycustomerfingerprint_fingerprint_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifycustomerfingerprint',
            name='customer_id',
            field=models.BigIntegerField(default=None, help_text='Shopify customer ID'),
        ),
    ]
