# Generated by Django 2.2.12 on 2020-07-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_store', '0004_auto_20200625_0449'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shopifycustomerfingerprint',
            constraint=models.UniqueConstraint(fields=('customer_id', 'fingerprint_title'), name='Customer and Title'),
        ),
    ]
