# Generated by Django 2.2.12 on 2020-07-10 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_store', '0005_auto_20200709_2039'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shopifycustomerfingerprint',
            name='Customer and Title',
        ),
        migrations.AlterUniqueTogether(
            name='shopifycustomerfingerprint',
            unique_together={('customer_id', 'fingerprint_title')},
        ),
    ]
