# Generated by Django 2.2.12 on 2020-07-10 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_store', '0006_auto_20200710_0821'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shopifycustomerfingerprint',
            constraint=models.UniqueConstraint(fields=('customer_id', 'fingerprint_title'), name='unique_customer_fingerprint_file'),
        ),
    ]
