# Generated by Django 2.2.12 on 2020-07-10 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_store', '0007_auto_20200710_0831'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shopifycustomerfingerprint',
            unique_together=set(),
        ),
    ]
