# Generated by Django 2.2.12 on 2020-08-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_store', '0008_auto_20200710_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='FingerprintRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=250)),
                ('from_email', models.EmailField(max_length=254)),
                ('to_email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fingerprint Request',
                'verbose_name_plural': 'Fingerprint Requests',
                'ordering': ('-created',),
            },
        ),
    ]
