# Generated by Django 2.2.12 on 2020-08-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_store', '0009_fingerprintrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='fingerprintrequest',
            name='receiver_name',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
