# Generated by Django 2.2.12 on 2020-08-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_store', '0010_fingerprintrequest_receiver_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fingerprintrequest',
            name='sender_name',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
