# Generated by Django 2.2.12 on 2020-08-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_store', '0011_fingerprintrequest_sender_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingerprintrequest',
            name='customer_id',
            field=models.BigIntegerField(),
        ),
    ]
