# Generated by Django 2.2.12 on 2020-08-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_store', '0012_auto_20200810_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerWishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.BigIntegerField()),
                ('customer_id', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Wishlist',
                'verbose_name_plural': 'Product Wishlist',
                'ordering': ('-created',),
            },
        ),
    ]
