# Generated by Django 2.2.12 on 2020-08-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_store', '0013_customerwishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSidebarNavigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=32)),
                ('slug', models.SlugField(default=None, max_length=32)),
                ('show_in_menu', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=None)),
            ],
            options={
                'verbose_name': 'Product Wishlist',
                'verbose_name_plural': 'Product Wishlist',
                'ordering': ('position',),
            },
        ),
    ]
