# Generated by Django 2.2.12 on 2020-08-11 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_store', '0014_appsidebarnavigation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appsidebarnavigation',
            options={'ordering': ('position',), 'verbose_name': 'App Sidebar Menu', 'verbose_name_plural': 'App Sidebar Menu'},
        ),
    ]
