# Generated by Django 2.2.12 on 2020-08-13 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_store', '0015_auto_20200811_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerwishlist',
            name='graphql_customer_id',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='customerwishlist',
            name='graphql_product_id',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='fingerprintrequest',
            name='graphql_customer_id',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='shopifycustomerfingerprint',
            name='graphql_customer_id',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='customerwishlist',
            name='customer_id',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='customerwishlist',
            name='product_id',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='fingerprintrequest',
            name='customer_id',
            field=models.BigIntegerField(default=None),
        ),
    ]
