# Generated by Django 2.2.12 on 2020-08-13 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_store', '0016_auto_20200813_0746'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerWishList',
            new_name='ShopifyCustomerWishList',
        ),
    ]
