# Generated by Django 2.2.12 on 2020-08-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_store', '0017_auto_20200813_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=120)),
                ('handle', models.CharField(default=None, max_length=120, unique=True)),
                ('show_in_menu', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=None)),
            ],
            options={
                'verbose_name': 'App Category',
                'verbose_name_plural': 'App Categories',
                'ordering': ('position',),
            },
        ),
    ]
