# Generated by Django 2.2.12 on 2020-08-18 15:00

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_store', '0018_appcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppHomepageBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('sub_heading', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('show_in_app', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=None)),
                ('image', imagekit.models.fields.ProcessedImageField(default=None, upload_to='homepage/banners/')),
            ],
            options={
                'verbose_name': 'Homepage Banner',
                'verbose_name_plural': 'Homepage Banners',
                'ordering': ('-position',),
            },
        ),
        migrations.CreateModel(
            name='AppHomepageSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('sub_heading', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('show_in_app', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=None)),
                ('image', imagekit.models.fields.ProcessedImageField(default=None, upload_to='homepage/slider/')),
            ],
            options={
                'verbose_name': 'Homepage Slider',
                'verbose_name_plural': 'Homepage Sliders',
                'ordering': ('-position',),
            },
        ),
    ]
