# Generated by Django 2.2.12 on 2020-08-19 19:32

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_store', '0019_apphomepagebanner_apphomepageslider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apphomepageslider',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default=None, upload_to='homepage/sliders/'),
        ),
    ]
