# Generated by Django 2.2.12 on 2020-08-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_store', '0020_auto_20200820_0132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appsidebarnavigation',
            old_name='title',
            new_name='access_route',
        ),
        migrations.RemoveField(
            model_name='appsidebarnavigation',
            name='slug',
        ),
        migrations.AddField(
            model_name='appsidebarnavigation',
            name='human_name',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AddField(
            model_name='appsidebarnavigation',
            name='icon',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='appsidebarnavigation',
            name='name',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
