# Generated by Django 2.2.12 on 2020-08-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_store', '0021_auto_20200820_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsidebarnavigation',
            name='method',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='appsidebarnavigation',
            name='access_route',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
