# Generated by Django 2.2.12 on 2020-08-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_store', '0023_shopifycustomerfcmdevice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopifycustomerfcmdevice',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='shopifycustomerfcmdevice',
            name='grapql_customer_id',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
