# Generated by Django 2.2.12 on 2020-08-24 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_store', '0024_auto_20200825_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopifycustomerfcmdevice',
            old_name='grapql_customer_id',
            new_name='graphql_customer_id',
        ),
    ]
