# Generated by Django 2.2.12 on 2020-09-04 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_store', '0025_auto_20200825_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsidebarnavigation',
            name='registered_user_only',
            field=models.BooleanField(default=False),
        ),
    ]
