# Generated by Django 2.2.12 on 2020-11-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_store', '0026_appsidebarnavigation_registered_user_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSidebarFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('tags', models.CharField(default=None, max_length=500, null=True, verbose_name='Tags')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Sidebar Filter',
                'verbose_name_plural': 'App Sidebar Filters',
                'ordering': ('title',),
            },
        ),
    ]
