# Generated by Django 2.2.12 on 2020-11-22 12:44

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('shopify_store', '0027_appsidebarfilter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsidebarfilter',
            name='tags',
        ),
        migrations.AddField(
            model_name='appsidebarfilter',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
