# Generated by Django 2.2.16 on 2020-11-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_store', '0028_auto_20201122_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsidebarfilter',
            name='position',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Position'),
        ),
    ]
