# Generated by Django 2.2.16 on 2021-01-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_store', '0029_appsidebarfilter_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCheckoutID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.BigIntegerField(default=None)),
                ('graphql_customer_id', models.CharField(default=None, max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer Checkout ID',
                'verbose_name_plural': 'Customer Checkout ID',
            },
        ),
        migrations.AlterModelOptions(
            name='appsidebarfilter',
            options={'ordering': ('position',), 'verbose_name': 'App Sidebar Filter', 'verbose_name_plural': 'App Sidebar Filters'},
        ),
    ]
