# Generated by Django 2.2.16 on 2021-01-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_store', '0030_auto_20210117_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercheckoutid',
            name='checkout_id',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
