# Generated by Django 2.2.16 on 2021-01-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_store', '0031_customercheckoutid_checkout_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercheckoutid',
            name='customer_id',
            field=models.BigIntegerField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='customercheckoutid',
            name='graphql_customer_id',
            field=models.CharField(default=None, max_length=250, unique=True),
        ),
    ]
