# Generated by Django 2.2.16 on 2021-01-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_store', '0032_auto_20210117_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercheckoutid',
            name='checkout_id',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
