# Generated by Django 2.2.16 on 2021-06-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_store', '0033_auto_20210117_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product3DModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.BigIntegerField(default=None, unique=True)),
                ('model_file', models.FileField(upload_to='3d_models/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer Checkout ID',
                'verbose_name_plural': 'Customer Checkout ID',
            },
        ),
    ]
