"""
Django settings for bobo_musu_3479 project.

Generated by 'django-admin startproject' using Django 1.11.16.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import environ

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

env = environ.Env()
# environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("SECRET_KEY", "kw=rsr8-2do9c0)tdud(vglyte@p3c4nr*@8sybg7wshw1@3%(")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

ALLOWED_HOSTS = env.list("HOST", default=["*"])
SITE_ID = 1

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites'
]
LOCAL_APPS = [
    'home',
    'users.apps.UsersConfig',
    'shopify_store.apps.ShopifyStoreConfig',
    # 'shopify_app.apps.ShopifyAppConfig',
    'shopify_admin.apps.ShopifyAdminConfig',
    'dashboard.apps.DashboardConfig',
]
THIRD_PARTY_APPS = [
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'bootstrap4',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'storages',
    'drf_yasg',
    'django_cleanup.apps.CleanupConfig',
    'imagekit',
    'fcm_django',
    'django_extensions',
    'taggit',
    'taggit_serializer',
]
if DEBUG:
    THIRD_PARTY_APPS += ['debug_toolbar', ]
INSTALLED_APPS += THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # 'shopify_app.middleware.LoginProtection',
]

if DEBUG:
    MIDDLEWARE += ['debug_toolbar.middleware.DebugToolbarMiddleware', ]
    INTERNAL_IPS = [
        # ...
        '127.0.0.1',
        # ...
    ]

ROOT_URLCONF = 'bobo_musu_3479.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            os.path.join(BASE_DIR, 'home/templates'),
            os.path.join(BASE_DIR, 'dashboard/templates'),
            os.path.join(BASE_DIR, 'shopify_admin/templates'),
            os.path.join(BASE_DIR, 'shopify_store/templates'),
            os.path.join(BASE_DIR, 'shopify_app/templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 'shopify_app.context_processors.current_shop',
            ],
        },
    },
]

WSGI_APPLICATION = 'bobo_musu_3479.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'db.sqlite',
    }
}

if env.str('DATABASE_URL', default=None):
    DATABASES = {
        'default': env.db()
    }

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
# DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

AWS_ACCESS_KEY_ID = env.str('AWS_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY = env.str('AWS_SECRET_ACCESS_KEY', '')
AWS_STORAGE_BUCKET_NAME = env.str('AWS_STORAGE_BUCKET_NAME', '')
AWS_S3_REGION_NAME = env.str('AWS_STORAGE_REGION', '')
AWS_QUERYSTRING_AUTH = env.bool('AWS_QUERYSTRING_AUTH', default=False)
AWS_DEFAULT_ACL = env.str('AWS_DEFAULT_ACL', '')
if DEBUG:
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend'
)

# allauth
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = None
LOGIN_REDIRECT_URL = '/'

if DEBUG:
    # output email to console instead of sending
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# EMAIL_HOST = 'smtp.sendgrid.net'
# EMAIL_HOST_USER = env.str('SENDGRID_USERNAME', '')
# EMAIL_HOST_PASSWORD = env.str('SENDGRID_PASSWORD', '')
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True

# shopify settings
SHOPIFY_SUBDOMAIN = env.str('SHOPIFY_SUBDOMAIN', '')
SHOPIFY_DOMAIN = env.str('SHOPIFY_DOMAIN', '')
SHOPIFY_API_VERSION = env.str('SHOPIFY_API_VERSION', '2020-04')
SHOPIFY_ADMIN_API_KEY = env.str('SHOPIFY_ADMIN_API_KEY', '')
SHOPIFY_ADMIN_API_PASSWORD = env.str('SHOPIFY_ADMIN_API_PASSWORD', '')
SHOPIFY_ADMIN_API_SECRET = env.str('SHOPIFY_ADMIN_API_SECRET', '')
SHOPIFY_API_KEY = env.str('SHOPIFY_API_KEY', '')
SHOPIFY_APP_PASSWORD = env.str('SHOPIFY_APP_PASSWORD', '')
SHOPIFY_APP_SECRET = env.str('SHOPIFY_APP_SECRET', '')
SHOPIFY_WEBHOOK_SIGNED_KEY = env.str('SHOPIFY_WEBHOOK_SIGNED_KEY', '')
SHOPIFY_STOREFRONT_ACCESS_TOKEN = env.str('SHOPIFY_STOREFRONT_ACCESS_TOKEN', '')

# SHOPIFY STORE ADMIN API URL
SHOPIFY_ADMIN_API_URL = "https://%s:%s@%s.myshopify.com/admin/api/%s" % (
    SHOPIFY_ADMIN_API_KEY, SHOPIFY_ADMIN_API_PASSWORD, SHOPIFY_SUBDOMAIN, SHOPIFY_API_VERSION
)
# Import local settings
# try:
#     from .local_settings import *
#
#     INSTALLED_APPS += DEBUG_APPS
# except:
#     pass

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        # 'drf_firebase_auth.authentication.FirebaseAuthentication',

    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
        # 'rest_framework_datatables.renderers.DatatablesRenderer',
    ),
    'DEFAULT_FILTER_BACKENDS': [
        # 'django_filters.rest_framework.DjangoFilterBackend',
        # 'rest_framework_datatables.filters.DatatablesFilterBackend',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
    'PAGE_SIZE': 12,
}

CORS_ORIGIN_ALLOW_ALL = True
X_FRAME_OPTIONS = ''
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SAMESITE = False
CSRF_TRUSTED_ORIGINS = ['*.myshopify.com']
CSRF_COOKIE_SAMESITE = None

FERNET_ENCRYPT_KEY = env.str('FERNET_ENCRYPT_KEY', '')
# ENCRYPT_FILE_PASSWORD = env.str('ENCRYPT_FILE_PASSWORD', '')
# FIELD_ENCRYPTION_KEY = os.environ.get('FIELD_ENCRYPTION_KEY', '')

FCM_DJANGO_SETTINGS = {
    "FCM_SERVER_KEY": env.str("FCM_SERVER_KEY", "")
}

TAGGIT_CASE_INSENSITIVE = True
# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'console': {
#             'class': 'logging.StreamHandler',
#         },
#     },
#     'root': {
#         'handlers': ['console'],
#         'level': 'WARNING',
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['console'],
#             'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
#             'propagate': False,
#         },
#     },
# }