export const primaryColor = '#D09B2C'
export const primaryTextColor = '#878181'
export const secondaryTextColor = '#FFF'
export const darkColor = '#000'
export const labelColor = '#807B7A'
export const subheaderTextColor = '#C5C4C4'
export const grayishBorderColor = '#E7E7E7'

export const primaryBackgroundColor = '#2E5372'
export const secondaryBackgroundColor = '#FFF'
export const goldishBackgroundColor = '#D0BB7D'
export const yellowBackgroundColor = '#C89C44'
export const blueBackgroundColor = '#30516C'
export const transparent = 'rgba(0,0,0,0.5)'
export const badgesCBackgroundColor = '#CC672A'